### ISSUE TITLE
Pet toggles do not function.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#12]
Various pet toggle variables do not function. Last tested 05/21

Using EchoPet dev build 11, no other plugins. Java 8 update 92, paperspigot dev 749.

- [x] Pet bat - perfectly fine. No data toggles to test.
- [x] Pet blaze - perfectly fine. Fire state can toggle on and off.
- [x] Pet cave spider - perfectly fine. No data toggles to test.
- [x] Pet chicken - perfectly fine. Can toggle baby state.
- [x] Pet cow - perfectly fine. Can toggle baby state.
- [x] Pet creeper - perfectly fine. Can toggle powered state on and off.
- [x] Pet enderdragon - perfectly fine. No data toggles to test.
- [x] Pet enderman - perfectly fine. Can toggle screaming state.
- [x] Pet endermite - perfectly fine. No data toggles to test.
- [x] Pet ghast - perfectly fine. No data toggles to test.
- [x] Pet giant - perfectly fine. No data toggles to test.
- [x] Pet guardian - perfectly fine. Elder state can toggle on and off.
- [x] Pet horse - broken. Toggling any horse markings resets variant.
- [x] Pet human won't be updated by you. Disable in the meantime? ~~Pet human - broken. Unable to test as it isn't compatible with server version.~~
- [x] Pet iron golem - perfectly fine. No data toggles to test.
- [x] Pet magma cube - perfectly fine. Various sizes can be toggled.
- [x] Pet mushroom cow - perfectly fine. Can toggle baby state.
- [x] Pet ocelot - perfectly fine. Can toggle baby state and all cat types.
- [x] Pet pig - perfectly fine. Can toggle baby and saddle state.
- [x] Pet pig zombie - perfectly fine. Baby state can toggle on and off.
- [x] Pet rabbit - broken. Can toggle baby state and first five types. Can't change type into killer rabbit.
- [x] Pet sheep - perfectly fine. Spawns in not sheared. Can toggle sheared state, wool color, and baby state.
- [x] Shulker pet removed/disabled. ~~Pet shulker - broken. Doesn't follow the player. Also perhaps add an option to toggle open state?~~
- [x] Pet silverfish - perfectly fine. No data toggles to test.
- [x] Pet skeleton - perfectly fine. Wither skeleton state can toggle on and off.
- [x] Pet slime - perfectly fine. Various sizes can be toggled.
- [x] Pet snowman - perfectly fine. Sheared state can be toggled on and off.
- [x] Pet spider - perfectly fine. No data toggles to test.
- [x] Pet squid - perfectly fine. No data toggles to test.
- [x] Pet villager - Perfectly fine. Can toggle baby state and all professions.
- [x] Pet witch - perfectly fine. No data toggles to test.
- [x] Pet wither - perfectly fine. Shield state can toggle on and off.
- [x] Pet wolf - perfectly fine. Can toggle baby state, tamed state, angry state ,and tamed collar color. 
- [x] Pet zombie - perfectly fine. Can toggle baby and villager state on and off.

**Comment by Borlea** [comment]
Almost all these work for me except wither skeleton, enderman screaming.

**Comment by mibby** [comment]
Make sure you are on the latest Spigot and try compiling with a clean repo with just the source in your 1.9 branch with craftbukkit 1.9-R0.1-SNAPSHOT set in the pom?

This was the shaded jar that I compiled from your repo.
https://www.dropbox.com/s/lhv000vokrc7j0y/EchoPet.jar?dl=0

**Comment by Borlea** [comment]
You are definitely running something different than mine it seems.. I highly doubt the minimal changes I have done would make a difference..

I made sure to update my craftbukkit and spigot..

**Comment by mibby** [comment]
Nope, still doesn't work for me with your version. 

After further testing, it seems to break when ProtocolLib is installed. Latest dev build here.
http://ci.dmulloy2.net/job/ProtocolLib/255/

**Comment by Borlea** [comment]
I've been testing with protocollib on the server the whole time with no issues.

EchoPet also doesn't use protocollib except for a wrapper that was for 1.7 & 1.8 which was removed as this I am not supporting past versions.

**Comment by mibby** [comment]
Huh. With the latest dev build of protocollib? 

With my EchoPets compile without protocollib dev 255, some toggles work again. (Cows still don't go baby.) With protocollib dev 255, the toggles don't work. For me the issue is narrowed down / related to the use of protocollib dev 255.

**Comment by Borlea** [comment]
EchoPets doesn't require to be compiled to protocollib, and having it on the server seems to not affect anything for me.. Something was messed up with your jar

**Comment by mibby** [comment]
The problem happens with your jar too though.

**Comment by Borlea** [comment]
It must be another plugin integrating with protocollib that is causing the issue.

**Comment by mibby** [comment]
You are right. It actually seems to be an issue with LibsDisguise. Removing it, toggling slime height works again. @NavidK0 

I will update the ticket with what data toggles still do not work with Libsdisguise removed.

**Comment by mibby** [comment]
These issues are still relevant without LibsDisguise installed, with protocollib installed.

```
- Can't toggle zombie to villager or baby.
- Can't toggle skeletons to wither skeletons.
- Can't toggle sheep sheared state, baby, or wool color.
- Can't toggle pig zombie baby. 
- Can't toggle pig saddle or baby. Also toggling the baby option turns on/off the saddle!
- Can't toggle mushroom cow baby.
- Can't toggle creeper powered.
- Can't toggle cow baby.
- Can't toggle chicken baby.
- Unable to test villager toggles since it is invisible. (Assuming also broken.)
- Unable to test rabbit, ocelot, wolf, or horse toggles since they crash the client / error. (Assuming also broken.)
```

**Comment by Borlea** [comment]
Any other plugins you know of that are integrating with protocollib? Or any other plugin that creates support between 1.8 & 1.9? As setting things to baby should be working..

**Comment by mibby** [comment]
With just ProtocolLib, EchoPets, and permissions installed, toggling baby doesn't work. Removing protocollib, still doesn't work.

**Comment by mibby** [comment]
Compatibility error even though it doesn't work with just EchoPets and a permissions plugin? :confused: There are still some toggles that don't function for me.

**Comment by mibby** [comment]
Going slightly insane. Not sure why you are marking this as unable to reproduce unless you are not testing yourself.

Using EchoPets dev build 5 and _only_ EchoPets plugin with PaperSpigot dev 488. Java 8 update 74 for reference if needed.

- [x] Pet bat - perfectly fine. No data toggles to test.
- [x] Pet blaze - perfectly fine. Fire state can toggle on and off.
- [x] Pet cave spider - perfectly fine. No data toggles to test.
- [ ] Pet chicken - broken. Can't toggle baby state.
- [ ] Pet cow - broken. Can't toggle baby state.
- [ ] Pet creeper - broken. Can toggle powered state on, but can't toggle it off.
- [x] Pet enderdragon - perfectly fine. No data toggles to test.
- [ ] Pet enderman - broken. Can't toggle screaming state.
- [x] Pet endermite - perfectly fine. No data toggles to test.
- [x] Pet ghast - perfectly fine. No data toggles to test.
- [x] Pet giant - perfectly fine. No data toggles to test.
- [x] Pet guardian - perfectly fine. Elder state can toggle on and off.
- [ ] Pet horse - broken. Unable to test as it crashes the client on spawn.
- [ ] Pet human - broken. Unable to test as it isn't compatible with server version.
- [x] Pet iron golem - perfectly fine. No data toggles to test.
- [x] Pet magma cube - perfectly fine. Various sizes can be toggled.
- [ ] Pet mushroom cow - broken. Can't toggle baby state.
- [ ] Pet ocelot - broken. Unable to test as it crashes the client on spawn.
- [ ] Pet pig - broken. Toggling baby state turns saddle on and off instead of turning into a baby. Toggling saddle does not function.
- [x] Pet pig zombie - perfectly fine. Baby state can toggle on and off.
- [ ] Pet rabbit - broken. Unable to test as it crashes the client on spawn.
- [ ] Pet sheep - broken. Spawns in already sheared. Unable to toggle baby state, sheared state, or wool color.
- [ ] Pet shulker - broken. Doesn't follow the player. Also perhaps add an option to toggle open state?
- [x] Pet silverfish - perfectly fine. No data toggles to test.
- [x] Pet skeleton - perfectly fine. Wither skeleton state can toggle on and off.
- [x] Pet slime - perfectly fine. Various sizes can be toggled.
- [x] Pet snowman - perfectly fine. Sheared state can be toggled on and off.
- [x] Pet spider - perfectly fine. No data toggles to test.
- [x] Pet squid - perfectly fine. No data toggles to test.
- [ ] Pet villager - broken. Unable to test as it spawns in invisible.
- [x] Pet witch - perfectly fine. No data toggles to test.
- [x] Pet wither - perfectly fine. Shield state can toggle on and off.
- [ ] Pet wolf - broken. Unable to test as it crashes the client on spawn.
- [ ] Pet zombie - broken. Baby state can be toggled on and off. Toggling to villager can be toggled on, but can't be toggled off. The zombie turns into a villager permanently when toggled once.

**Comment by Borlea** [comment]
Can this be tested on build the latest [build](http://jenkins.codingforcookies.com/job/EchoPet/)

**Comment by mibby** [comment]
@Borlea Updated ticket. Current issues are creeper powered can't be toggled off, horse types make the horse invisible, can't test horse chested since I can't get the horse to a donkey/mule, horse armor has a 'black bunny type' listed, pet rabbit can't be toggled into a killer rabbit state, and zombies still can't be toggled back into a normal zombie after being toggled once to villager.

**Comment by mibby** [comment]
Also a slight bug with the GUI display for the pet wolf.

Toggle the 'tamed' state on. Close GUI. Then toggle 'angry' state on. Close GUI. The 'tamed' state will output '[TOGGLE ON]' when hovering over the option in the GUI when opening again.

Now toggle the 'tamed' state again to turn it on. Close GUI. Then re-open the GUI. The 'angry' state does not toggle off in the GUI, while the pet is no longer angry. It still outputs '[TOGGLE OFF]' on hover.

**Comment by Borlea** [comment]
kk I forced build 12, it should have the last 4 commits.. I'll be heading off for the day but hopefully it all the fixes work properly.

**Comment by mibby** [comment]
Re-tested as of dev 12.

Rabbit still can't be toggled into a killer rabbit type.
Horse types make the horse go invisible.

Those seem to be the remaining issues since Shulker is disabled and human won't be updated. :)

**Comment by Borlea** [comment]
Just those two and a few features/improvements which I'll do after release. Thanks for the help :)

But yah.. no clue if I'll be able to fix the yaw/pitch horse stuff, I know where in the code it happens I just don't think it is possible to override it.

The horse bug is rather interesting.. Might take a bit of work, just noticed killer rabbit isn't working but hopefully it wont take long

**Comment by mibby** [comment]
Sure, no problem. :) I helped DSH105 a lot back in the day when he still maintained the project. I'll be here to help you too if I run into any problems. 

No rush on the last two fixes. Killer rabbit isn't as important, but fixing invisible horses when selecting a type could be considered  high on the priority list - just so there aren't invisible entity complaints. 

The orientation reset bug isn't too much of a problem. Just something odd I noticed happening.

**Comment by Borlea** [comment]
@mibby maybe you can test horses and rabbits on the latest version and tell me if its all fixed?

**Comment by mibby** [comment]
@Borlea On dev 11, can't toggle rabbit to killer rabbit. Horse types work now, but changing markings resets the horse variant.

**Comment by Borlea** [comment]
As of the last few commits the killer bunny & gold rabbit types have been added/fixed
